### ISSUE TITLE
Release Components Documentation

### ISSUE THREAD

**Issue by razvan** [theministry/feature-tracker#52]
As a user of the SDP I want to know for every platform release:

1. What components are included (at the application level)?
    * version
    * status (deprecated, long-term-support, supported)
2. What container images are part  the release?

This information should be part of the feature tracker ([Stackable Feature Tracker](https://features.stackable.tech/)) and it should be generated automatically for every release.

```[tasklist]
### TODO
- [ ] UI for managing product lifecycle attributes (the `product_lifecycle.support_status` field)
- [ ] https://github.com/stackabletech/feature-tracker/pull/53
- [ ] https://github.com/stackabletech/docker-images/pull/528
- [ ] ...
```

# Acceptance criteria

* ~~There is a script that given a release name, generates a RBOM file.~~ We decided against an SBOM file and instead just update the database directly.
* There is a script or an API endpoint that given a RBOM file, updates the feature tracker DB.
  ** See: https://github.com/stackabletech/docker-images/pull/528
* The feature tracker UI is updated to reflect the RBOM contents.

# Implementation ideas

* ~~Prerequisite: The component status should be pinned down in some form before adding it to the RBOM.~~ This is now managed directly in the database.

* **Deprecated** : ~~Generate a release bill of materials for each release. (cyclone dx, json). This will be at the application level but will not get down to the package level.~~
    * Should contain the image references
       1. Location (docker.stackable.tech...)
       4. PURL pkg:docker/customer/dockerimage@sha256:244fd47e07d1004f0aed9c?repository_url=gcr.io
       5. A reference (BOM link) to the SBOM of the image
  
* **Deprecated** : This in formation is in the database. ~~The RBOM should also contain the application/product names and versions.~~
    * Question: Should additional components also be included in the MVP ? Ex: vector, python, etc. 

* If an operator patch release is made, everything in the platform is also released in lock-step.

# Questions

* How should this be presented in the Feature Tracker?
    Eg: Just a table of Release, Product+version, Status for now?
* Do we want the presentation to determine the data model, or do we need to think ahead (linking SBOMs, dependencies, CVEs, etc...) and define how it is presented later?

# **Deleted because deprecated for this issue**. ~~Example component in a SBOM file (cyclone dx):~~

* Adding the component status is possible via properties.
* There is a stackable namespace reserved already: https://github.com/CycloneDX/cyclonedx-property-taxonomy
```
deleted
```
# Links

* CycloneDX json reference: https://cyclonedx.org/docs/1.5/json/

**Comment by NickLarsenNZ** [comment]
Are there any initial ideas on where the source of truth is (looking at the code I see an API and DB connection), and how that will be serialized/transported to the Feature Tracker (presumably the API in this repo)?

**Comment by NickLarsenNZ** [comment]
1. How should this be presented in the Feature Tracker?
   - Eg: Just a table of Release, Product+version, Status for now?
2. Do we want the presentation to determine the data model, or do we need to think ahead (linking SBOMs, dependencies, CVEs, etc...) and define how it is presented later?
